### ISSUE TITLE
Add audit logging for event consumption

### ISSUE THREAD

**Issue by timmc-edx** [openedx/event-bus-kafka#111]
We currently don't have a complete record of when we consumed an event from the broker and then how long it took to process. These would be important information for debugging consumer latency and other issues; right now it's hard to get a picture of how e.g. a slow-to-process event affects the latency of following events, or whether there is a large gap in incoming events that correlates with DB lost connection errors.

New Relic has some information, but due to sampling we don't have a complete picture. (Usually we record information for 99+% of events, but over a 1 month window I see average capture drop as low as 70%. This may be due to heavier loss during replays.) Our logs also have some information, but only for errors.

We'll start by logging all received and processed events -- not necessarily in full detail, but enough for debugging. If at some point we're generating enough log data that it's a problem, we can add feature toggles or otherwise reassess our approach.

A/C:

- [x] Log metadata when an event is received: Key, topic, partition, offset, timestamp when received, production timestamp (if available)
- [x] Log when an event is done processing: Key, topic, partition, offset, timestamp, receiver output. May need to unify with error handler.
- [x] Log when and event is produced with: Key, topic, timestamp 
- [x] Small ADR explaining the need for audit logging

**Comment by robrap** [comment]
Thanks for the ticket.
1. Are there any other bits of metadata we want to add in or leave out? See https://github.com/openedx/openedx-events/blob/main/openedx_events/data.py#L25-L32
2. Do we want any audit from the produce callback?
3. If so, do we want to drop any redundant metadata from the producer?
4. Do we want to add any other consumer-side metadata like the proposed timestamp (e.g. library version)?

**Comment by robrap** [comment]
[question] What do we have in Datadog (from Confluent Kafka metrics) at this time?

**Comment by robrap** [comment]
1. New Relic does contain (sampled?) transactions for each message and its duration. See https://onenr.io/0vwBpDmz8jp. We could pull the offset and partition and count to understand how much sampling.
2. The main point of this ticket is to add additional audit details in the logs if samplings proves to lose too much data to debug effectively.

**Comment by robrap** [comment]
From @timmc-edx:
> [inform] To answer the question of whether NR is sampling Kafka information, I ran this query: from Transaction select max(kafka_offset) - min(kafka_offset), count(*) where appName = 'prod-edx-discovery' facet kafka_partition since 2 days ago Turns out it actually matches up, with the exception of what is probably just an off-by-one issue. Out to 14 days, there might be a couple of missing events, but at least 99.9% of them are there.

> [However,] I think we lose enough information that the ticket is still basically correct. And I suspect it's especially likely to happen during replays, which is one of the times when I really want to know exactly what happened.

**Comment by timmc-edx** [comment]
Updated ticket with more info on NR loss rate.

**Comment by timmc-edx** [comment]
Added https://github.com/openedx/event-bus-kafka/issues/128 for a remaining bug that we can probably punt on for now.
