### ISSUE TITLE
Update the event bus how-to with more detailed instructions

### ISSUE THREAD

**Issue by rgraber** [openedx/event-bus-kafka#116]
# Acceptance Criteria
- [ ] A new developer can follow the how-to to use the event bus locally with either a local Kafka cluster or the edx-dev one

# Notes
* Make sure to include suggestion to prefix consumer group names to avoid interfering with other developers (eg rgraber_course_catalog_dev)

**Comment by robrap** [comment]
@rgraber: It probably makes sense for you to do the updates, and for someone else to try it out (or at least read the updates). Can we just mark this as groomed and assign to you?

**Comment by rgraber** [comment]
On further reflection, I think it's better to update https://2u-internal.atlassian.net/wiki/spaces/AT/pages/174555142/How+to+Use+the+Event+Bus+edX.org+1+of+2 since using the dev cluster is 2u-only information. I have added info there.
