### ISSUE TITLE
Add annotations for event bus settings

### ISSUE THREAD

**Issue by robrap** [openedx/event-bus-kafka#124]
AC:
- [x] Add annotation documentation for the rest of the settings in `config.py`.

Only one of the settings in `config.py` is annotated: https://github.com/openedx/event-bus-kafka/blob/bb4262f64b6361bbc7b1d8c621e7f74270f3bda4/edx_event_bus_kafka/internal/config.py#L88-L95

This ticket is for adding annotations for the rest of the settings in this file.
https://github.com/openedx/event-bus-kafka/blob/main/edx_event_bus_kafka/internal/config.py

We might want to link to the new annotations from:
* https://github.com/openedx/event-bus-kafka#documentation
* https://openedx.atlassian.net/wiki/spaces/AC/pages/3508699151/How+to+start+using+the+Event+Bus#First-time-setup

Note: We could consider updating docs in this library to extract/publish these annotations, as is done in edx-platform. This could be part of this ticket or its own ticket.

**Comment by robrap** [comment]
Should we do this now, or add to Future milestone?

**Comment by timmc-edx** [comment]
Created https://github.com/openedx/event-bus-kafka/issues/139 or followup.
