### ISSUE TITLE
[producer] Message ID not included in audit log when event delivered

### ISSUE THREAD

**Issue by timmc-edx** [openedx/event-bus-kafka#128]
As of 3.9.2, the consumer's audit logging includes a `message_id=<UUID>` but the producer is logging `message_id=None`.

We can still uniquely identify a message _within_ a topic, since we have topic + partition + offset. However, once we start using dead letter queues, retry queues, the outbox pattern—anything where a message might be copied between topics, or be delayed in delivery to a topic—then we'll need to start logging the message_id correctly as well.

- [x] https://github.com/openedx/event-bus-kafka/pull/129
- [x] Upgrade edx-platform to 3.9.3 (https://github.com/openedx/edx-platform/pull/31751) and confirm in logs

**Comment by robrap** [comment]
Does it include partition and offset, and this is just redundant, but potentially useful data? Thanks.

**Comment by timmc-edx** [comment]
Yes -- I'll update ticket to explain that.

**Comment by timmc-edx** [comment]
Turns out `evt.headers()` is always None in the callback: https://github.com/confluentinc/confluent-kafka-python/issues/574
