### ISSUE TITLE
[Documentation] Catalog what has currently been implemented

### ISSUE THREAD

**Issue by rgraber** [openedx/event-bus-kafka#158]
Possible columns: Producing Service, topic name(s? stage/prod), event(s), Known Consuming Services

**Comment by robrap** [comment]
See https://2u-internal.atlassian.net/wiki/spaces/AT/pages/174555142/How+to+Use+the+Event+Bus+edX.org+2+of+2#Current-event-bus-usage

**Comment by timmc-edx** [comment]
Is this ticket complete? I see it in the Done column on our board but it is still open.
