### ISSUE TITLE
Use TopicRecordName strategy on serialization

### ISSUE THREAD

**Issue by rgraber** [openedx/event-bus-kafka#164]
A/C

- [x] Schemas are registered using topicrecordname instead of topicname
- [x] Documentation has updated guidance for naming topics

Add `conf={'subject.name.strategy': topic_record_subject_name_strategy}` to key_ and value_serializers

**Comment by robrap** [comment]
* Note: We think this should be blocked until the remove signal work is complete.
* @rgraber: Please link branch or PR.

**Comment by rgraber** [comment]
https://github.com/openedx/event-bus-kafka/blob/a86f90a4445a54cc283bf7a68f9c5efef3d3cc0c/edx_event_bus_kafka/internal/producer.py#L169
