### ISSUE TITLE
[Abstraction] Implement consumer API for event-bus-kafka

### ISSUE THREAD

**Issue by dianakhuang** [openedx/event-bus-kafka#19]
PR https://github.com/openedx/openedx-events/pull/200 adds a consumer API to openedx-events. event-bus-kafka currently has its own consumer management command, but we should switch to using the provided one.

## Acceptance Criteria
- [ ] Implement the consumer API
  - See this [old branch](https://github.com/openedx/event-bus-kafka/compare/main...timmc/consumer-api) for roughly what that will look like, although the planned API has since changed.
  - [ ] Remove the existing management command, which has a colliding name
  - [ ] This is a breaking change, so use a major version bump
- [ ] Use in course-discovery
  - [ ] Upgrade course-discovery to latest version of openedx-events
  - [ ] Add it to the INSTALLED_APPS
  - [ ] Remove `course_discovery/apps/course_metadata/management/commands/consume_events.py` (name collides with openedx-events)
- [ ] 2U: Update course-discovery workers to new management command format

## Additional Notes
- This ticket was originally about creating a consumer API abstraction, but is now about implementing it for the Kafka impl
- See https://github.com/openedx/openedx-events/issues/87 for the producer API

**Comment by robrap** [comment]
We think the config code will basically cover this (see https://github.com/openedx/openedx-events/issues/87), and if not, we (or the community) will ticket this abstraction work when we are clear on what is needed.

**Comment by robrap** [comment]
Re-opening this ticket. See https://github.com/openedx/openedx-events/pull/200#issuecomment-1515143501.

**Comment by robrap** [comment]
@timmc-edx: Feel free to update this ticket as appropriate. Not sure what parts of this ticket are complete, and what is remaining.
