### ISSUE TITLE
Move kafka reusable consuming code to kafka-event-bus

### ISSUE THREAD

**Issue by robrap** [openedx/event-bus-kafka#2]
- [x] Copy edx-arch-experiments ADRs from https://github.com/edx/edx-arch-experiments/tree/main/edx_arch_experiments/kafka_consumer/docs/decisions to top-level docs/decisions folder in kafka-event-bus.
- [x] Update OEP PR links to these ADRs. (https://github.com/openedx/open-edx-proposals/pull/324)
    - https://github.com/openedx/open-edx-proposals/pull/360
- [x] Copy edx-arch-experiments kafka-consumer to submodule of kafka-event-bus.

**Comment by timmc-edx** [comment]
Left unfinished: Removing old code from edx-arch-experiments. It's unclear whether we want to do so since there's benefit in having a working example plugin...
