### ISSUE TITLE
Pin newrelic to <8.2.0

### ISSUE THREAD

**Issue by rgraber** [openedx/event-bus-kafka#51]
newrelic==8.2.0 has broken instrumentation for confluent-kafka. This constraint can be removed once this issue is fixed. 

The New Relic support ticket is here (you will need to ask @robrap for access): https://support.newrelic.com/s/case-details?caseId=5008W00000ufMOXQA2&isCollaborator=false

The issue to remove this constraint is https://github.com/openedx/event-bus-kafka/issues/52

**Comment by timmc-edx** [comment]
NR has merged [a fix](https://github.com/newrelic/newrelic-python-agent/pull/645/files#diff-12751058a477e81b1424ca880c0985c76e820d0ef3dea108c5eb450858303c9fR68) for the issue, although it's not yet released.
