### ISSUE TITLE
Unpin newrelic

### ISSUE THREAD

**Issue by rgraber** [openedx/event-bus-kafka#52]
newrelic was pinned in https://github.com/openedx/event-bus-kafka/issues/51 . We should remove this constraint once the instrumentation of Confluent Kafka is fixed.

The New Relic support ticket is here (you will need to ask @robrap for access): https://support.newrelic.com/s/case-details?caseId=5008W00000ufMOXQA2&isCollaborator=false

https://github.com/openedx/edx-platform/pull/31119 was the PR to pin newrelic to an unreleased version

**Comment by robrap** [comment]
Waiting on the actual release of the fix.

**Comment by rgraber** [comment]
The pinning was addressed in https://github.com/openedx/edx-platform/pull/31119 (note that's in edx-platform)

**Comment by timmc-edx** [comment]
NR v8.2.1 has been released.
