### ISSUE TITLE
Separate error handling around event serialization

### ISSUE THREAD

**Issue by timmc-edx** [openedx/event-bus-kafka#68]
We have a try-block around event production overall, but the part where we serialize event data involves a call to the schema registry. This should be wrapped in a separate try-block so that it can be distinguished from broker or queue issues.

**Comment by robrap** [comment]
@timmc-edx: I don't think this is really needed. I think all the broker/queue issues will eventually make it to the delivery callback, which has a different block. And, if I'm wrong, either way we'll get the actual error which will help us differentiate. As-is, the code is simpler and probably provides the same result.

**Comment by timmc-edx** [comment]
Yeah, it seemed like a good idea at the time, but I agree with you now. :-)
