### ISSUE TITLE
[Consumer] Switch to manual offset commits

### ISSUE THREAD

**Issue by timmc-edx** [openedx/event-bus-kafka#72]
Acceptance Criteria

- [x] Set `enable.auto.commit` to false.
- [x] Offset is manually committed at the end of each iteration of the message processing loop.

Kafka [defaults to `enable.auto.commit=true`](https://kafka.apache.org/documentation/#consumerconfigs_enable.auto.commit) every [5 seconds](https://kafka.apache.org/documentation/#consumerconfigs_auto.commit.interval.ms), which could lead to an increased rate of both duplicate message processing (if consumer shuts down after processing a message but before autocommit) and dropped messages (if a consumer encounters a temporary error that should lead to rejection and reprocessing).

Duplicate processing should be acceptable, but at such time as we have a way of distinguishing between temporary and permanent errors, we may want to switch to manual commits as a way of avoiding dropped messages.

**Comment by robrap** [comment]
@timmc-edx: FYI: I moved this to the Production ready milestone.
